-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.autobuses
(
    id_autobuses serial NOT NULL,
    "añoFabricacion" integer NOT NULL,
    precio numeric(10, 4) NOT NULL,
    PRIMARY KEY (id_autobuses)
);

CREATE TABLE IF NOT EXISTS public.conductores
(
    id_conductor serial,
    nombre character varying(60) NOT NULL,
    edad integer,
    PRIMARY KEY (id_conductor)
);

CREATE TABLE IF NOT EXISTS public.lugares
(
    id_lugar serial NOT NULL,
    nombre character varying(60) NOT NULL,
    PRIMARY KEY (id_lugar)
);

CREATE TABLE IF NOT EXISTS public.rutas
(
    id_ruta serial,
    id_autobus integer NOT NULL,
    id_conductor integer NOT NULL,
    id_lugar integer NOT NULL,
    f_ruta date NOT NULL,
    PRIMARY KEY (id_ruta)
);

ALTER TABLE IF EXISTS public.rutas
    ADD CONSTRAINT fk_rutas_autobuses FOREIGN KEY (id_autobus)
    REFERENCES public.autobuses (id_autobuses) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.rutas
    ADD CONSTRAINT fk_rutas_conductores FOREIGN KEY (id_conductor)
    REFERENCES public.conductores (id_conductor) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.rutas
    ADD CONSTRAINT fk_rutas_lugares FOREIGN KEY (id_lugar)
    REFERENCES public.lugares (id_lugar) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;