-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.zoo
(
    id_zoo serial,
    nombre character varying(60) NOT NULL,
    ciudad character varying(60) NOT NULL,
    pais character varying(60) NOT NULL,
    tamano numeric(10, 2) NOT NULL,
    presupuesto_anual integer NOT NULL,
    PRIMARY KEY (id_zoo)
);

CREATE TABLE IF NOT EXISTS public.especie
(
    id_especie serial,
    n_vulgar character varying(60) NOT NULL,
    n_cientifico character varying(60) NOT NULL,
    familia character varying(60) NOT NULL,
    extincion boolean NOT NULL,
    PRIMARY KEY (id_especie)
);

CREATE TABLE IF NOT EXISTS public.animal
(
    id_animal serial,
    sexo character(1) NOT NULL,
    ano_nacimiento integer NOT NULL,
    pais_origen character varying(60) NOT NULL,
    continente character varying(60) NOT NULL,
    id_especie integer,
    id_zoo integer,
    PRIMARY KEY (id_animal)
);

ALTER TABLE IF EXISTS public.animal
    ADD CONSTRAINT fk_animales_zoo FOREIGN KEY (id_zoo)
    REFERENCES public.zoo (id_zoo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.animal
    ADD CONSTRAINT fk_animales_especie FOREIGN KEY (id_especie)
    REFERENCES public.especie (id_especie) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;